#cloud-config

hostname: <host>
manage_etc_hosts: true

# You could modify this for your own user information
users:
  - name: <user>
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: <password>
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }
    ssh-authorized-keys:
      - <ssh-key>

# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "Europe/Berlin"

# # Update apt packages on first boot
package_upgrade: false

# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'
